### ISSUE TITLE
JsonObject Map and elasticsearch

### ISSUE THREAD

**Issue by ValCapri** [englishtown/vertx-elasticsearch-service#11]
I saw that you are using getMap of JsonObject and it seems not to work correctly with ElasticSearch.
It seems to be best to use encode() and pass the encoded Json directly.

Otherwise, I get this : 
'financial' {
  'income=1400'
}

I should get this : 
'financial' {
  'income':1400
}

**Comment by adrianluisgonzalez** [comment]
Thanks for the input.   Can you provide steps to reproduce or an example?

**Comment by newoga** [comment]
Maybe this isn't an issue anymore since we've replaced nearly every use of `.getMap()` with `.encode()`.

The only two places I see the use of `.getMap()` is in the `DefaultElasticSearchService` for [script](https://github.com/englishtown/vertx-elasticsearch-service/blob/17a2bf8d49f0835877dd228aef9036fde935b635/src/main/java/com/englishtown/vertx/elasticsearch/impl/DefaultElasticSearchService.java#L131) and [template](https://github.com/englishtown/vertx-elasticsearch-service/blob/17a2bf8d49f0835877dd228aef9036fde935b635/src/main/java/com/englishtown/vertx/elasticsearch/impl/DefaultElasticSearchService.java#L251) parameters

**Comment by adrianluisgonzalez** [comment]
I agree with @newoga, I don't think this is an issue any more and haven't heard back from @ValCapri.

**Comment by ValCapri** [comment]
@adrianluisgonzalez : I just tested in the app where I was having the issue and it's gone with the latest version. Sorry for the delay to reply but I was unable to reply (vision impaired).
